default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: raritan_dev

test:
  <<: *default
  database: raritan_test

production:
  <<: *default
  database: raritan_prod
