development:
  adapter: postgresql
  encoding: unicode
  database: raritan_development
  host: localhost
  pool: 5
  user: superhot
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: raritan_test
  pool: 5
  host: localhost
  password:
